os:
  - linux
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run build
cache: npm
after_success:
  - npx tap --coverage-report=text-lcov | npx codecov
