os:
  - linux
  - osx
language: node_js
node_js:
  - "10.14"
  - "10"
  - "12"
  - "13"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
  - yarn build
  - yarn test:application
cache: yarn
after_success:
  - yarn codecov --disable=gcov -F unittests
