name: Node.js CI

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16, 10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lock-file
      - run: yarn build
      - run: yarn test
        env:
          CI: true
      - run: yarn test:application
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
