name: Node.js CI

on:
  push:
    branches: [v*]
  pull_request:
    branches: [v*]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16, 10.x, 12.x, 14.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lock-file
      - name: Build project
        run: yarn build
      - name: Lint project
        run: yarn lint
      - name: Run tests on library
        run: yarn test
        env:
          CI: true
      - name: Run tests on application
        run: yarn test:application
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
